export const TICKETS_FETCHING = 'TICKETS_FETCHING'
export const TICKETS_FETCHED = 'TICKETS_FETCHED'
export const TICKETS_FETCH_ERROR = 'TICKETS_FETCH_ERROR'
export const TICKETS_TOGGLE_RESOLVED = 'TICKETS_TOGGLE_RESOLVED'
